name: Build App

on:
    push:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
                python-version: [3.12]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}

            - name: Store Architecture (Windows)
              if: matrix.os == 'windows-latest'
              run: |
                  echo "ARCHITECTURE=x86_64" >> $env:GITHUB_ENV
            -   name: Build Executable (Windows)
                if: matrix.os == 'windows-latest'
                uses: Nuitka/Nuitka-Action@main
                with:
                    nuitka-version: 'main'
                    script-name: |
                        test.py
                    mode: standalone
                    mingw64: true

            -   name: tree command (Windows)
                if: matrix.os == 'windows-latest'
                run: |
                    Get-ChildItem -Recurse "build\"

            -   name: Upload artifacts Windows
                if: matrix.os == 'windows-latest'
                uses: actions/upload-artifact@v4
                with:
                    name: '${{ matrix.os }}_${{ env.ARCHITECTURE }}-build'
                    path: 'build\'
                    include-hidden-files: 'true'
